name: Publish Package to NPM Registry

on:
  release:
    types: [created]

jobs:
  build:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          scope: '@bklyn-labs'
      - run: yarn install
      - run: yarn pack
      - run: npm adduser --scope=@bklyn-labs
      - run: npm publish --access=public --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
