name: Publish Package to NPM Registry

on:
  release:
    types: [created]

jobs:
  build:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          scope: '@bklyn-labs'
      - run: yarn install
      - run: yarn pack
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
