name: Publish Package to NPM Registry

on:
  release:
    types: [created]

jobs:
  build:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: pack
      - uses: borales/actions-yarn@v2.3.0
        with:
          auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
          cmd: publish
